### ISSUE TITLE
Where do I find the jar files 

### ISSUE THREAD

**Issue by grajee-everest** [elastacloud/spark-excel#10]
I would want to use the drivers/jars/packages to read excel files. Where can I find them to download?

**Comment by dazfuller** [comment]
If you look at the [releases](https://github.com/elastacloud/spark-excel/releases) section the jar files are attached with each version.

I'll add something to the README to make that more apparent 🙂

**Comment by dazfuller** [comment]
I've updated the README to include the download instructions as described previously. Let me know if you're all good and I'll close the issue.

**Comment by grajee-everest** [comment]
I see the jar files and thank you very much. I'm new to all these. Is there a sample pyspark code to that I can try?

**Comment by dazfuller** [comment]
The JAR is a fat jar and bundles everything it needs except for Spark (naturally). It needs to be in the classpath so that Spark can find it, how you do this depends on which platform you're using.

If you're using Databricks then have at their [library](https://docs.databricks.com/libraries/) docs. If it's Azure Synapse then their [docs](https://docs.microsoft.com/azure/synapse-analytics/spark/apache-spark-azure-portal-add-libraries) cover how to install a new library.

If you're running locally and using pyspark then you can do the following:

```bash
$ pyspark --jars file1.jar,file2.jar
```

Or you can use the [spark configuration](https://spark.apache.org/docs/latest/configuration.html#runtime-environment) (see `spark.jars`)

**Comment by grajee-everest** [comment]
daz - Thank you very much. I was able to test it successfully in **Azure Databricks** as well as **SQLServer 2019 Big Data Cluster**.

In Databricks, I was able to load the FAT Jar via the library module and use it directly

On SQLServer BDC, I had to download the FAT Jar into the HDFS drive and use CONFIG to refer to the JAR.

```
%%configure -f
{"conf": {"spark.jars": "hdfs:///modules/jar/elastacloud/spark-excel-3.1.2_0.1.7.jar"}
}

df = spark.read.format("com.elastacloud.spark.excel").load("/test/users.xls")

df.show()
```

**Comment by dazfuller** [comment]
Glad you got it working. Also nice to hear it working on a SQL 2019 Big Data Cluster as it's not an environment I've tried it out on.

Hopefully you can get that data out of Excel successfully 🙂
