### ISSUE TITLE
Join forces with crealytics/spark-excel?

### ISSUE THREAD

**Issue by nightscape** [elastacloud/spark-excel#12]
Hi @dazfuller,

I only discovered this project a few days ago.
I'm not sure if you were aware of https://github.com/crealytics/spark-excel ?
If yes, did you have a specific reason to start a new project (maybe you deemed it too much effort to do the upgrade to DataSource V2 in an existing codebase, or were not happy with the code quality)?
Do you think it makes sense to join forces?
At the moment we actually have a few active contributors, but for a long time it was myself only, so if we split the few open source contributors between two projects, there would be a lot of duplicated effort.

Let me know what you think!

**Comment by dazfuller** [comment]
Hi @nightscape 

I had heard of the Crealytics library before, but the reason for me starting this project was actually more about learning about the DataSource V2 apis. I'd just happened to had been doing some extensive parsing of Excel in C# using the NPOI library and so this seemed like a good place to start. Once it was working it didn't seem right to keep it to myself, and I was pretty opinionated about features, such as not wanting to implement a writer because people shouldn't be going back to Excel 😄
