### ISSUE TITLE
CONCAT function not supported

### ISSUE THREAD

**Issue by tahls** [elastacloud/spark-excel#14]
Hi @dazfuller,

I've been playing around with this project and have been loving it so far! 
However I've just attempted to read an Excel that uses the CONCAT function and it is throwing a parsing error for me (the specific error is **Caused by: org.apache.poi.ss.formula.eval.NotImplementedFunctionException: _xlfn.CONCAT**).

Looking through some other issues I came across this issue stating that CONCAT is now available with a newer version of the POI library: https://stackoverflow.com/a/66630395

Is it possible to get the POI library updated in a new version of the .jar?

**Comment by dazfuller** [comment]
It's certainly something I've been wanting to look at. I did try a few months ago and ran into some issues with newer versions, but it's worth revisiting.

**Comment by dazfuller** [comment]
ClassNotFound error in Azure Synapse for Spark pools for org.apache.commons.io.output.UnsynchronizedByteArrayOutputStream turns out to be an issue with Synapse using a really old version of the Apache commons-io library (2.5.0 in Synapse, 2.8.0 in Databricks). The POI library has a dependency on the class which was introduced in version 2.7.0.

Worth noting that 2.5.0 is still open to 2 known CVEs

**Comment by dazfuller** [comment]
Closing as this is now resolved as a result of PR #16
